### ISSUE TITLE
Messed up loading-order preventing OM from integrating correctly

### ISSUE THREAD

**Issue by Th3Shadowbroker** [Th3Shadowbroker/OuroborosMines#43]
**Describe the bug**
@ItaloPlcl reported issues with the BeautyQuests support (Requested in #39, Merged in #42).
For some reason, the support modules arent' loading correctly. This also affects PAPI and Jobs support!

**To Reproduce**
Unknown. Even if I use the same plugin version, the error does not occurr.
However, the log files from @ItaloPlcl show, that OM isn't loading as expected.
The same goes for BQ.

**Expected behavior**
OM and BQ loading normally and in the correct order.

**Desktop (please complete the following information):**
 - Minecraft-version: 1.16.3
 - Server-version: 1.16.3 Paper

**Additional context**
See discord for additional context.

**Comment by Th3Shadowbroker** [comment]
### What has been done/tested so far
- [ ] We're using the same paper version.
- [ ] OM jar is valid.
- [ ] BQ jar is valid.
- [ ] RedProtect doesn't affect the loading process (still has to be completly confirmed).
- [ ] Restarted the server completely after updating BQ and OM to their latest version.
- [ ] Test plugins 1-by-1 (Currently done by ItaloPLcl)

**Comment by Italoplcl** [comment]
this weekend I will try to continue testing, while I'm testing with another quest plugin
Thank you very much for your time and concern

**Comment by Th3Shadowbroker** [comment]
You're welcome 🙂 
Any news regarding the testing?

**Comment by Italoplcl** [comment]
I couldn't come up with a solution, I just switched from simplequest to quests and I had no problems.

**Comment by Th3Shadowbroker** [comment]
What about the other plugins that are supported by OM? Is Jobs and PAPI support loaded correctly?

**Comment by Th3Shadowbroker** [comment]
> What about the other plugins that are supported by OM? Is Jobs and PAPI support loaded correctly?
> That way I can ensure, that it isn't caused by OM itself ^^

Hey @Italoplcl, have you experienced any problems with one of these 🔼 and/or can you see the support for those plugins getting enabled by OM on server startup?

As it seems everything's working fine for quite some time now, I'm wondering if there were or are any further problems 🙂

**Comment by Italoplcl** [comment]
everything is fine here

**Comment by Th3Shadowbroker** [comment]
Alright 👍🏼
