### ISSUE TITLE
Logs facing wrong way

### ISSUE THREAD

**Issue by Lorenzostuy** [Th3Shadowbroker/OuroborosMines#48]
**Describe the bug**
Logs aren't replaced the correct way

**To Reproduce**

place logs, and mine the log.

**Expected behavior**
correctly sided log

**Screenshots**
![image](https://user-images.githubusercontent.com/47482523/103106855-5189d600-4639-11eb-809a-a1d9fdf46ebf.png)

**Desktop (please complete the following information):**
 - Minecraft-version: tuinity version git-tuinity-"8056d13"
 - Server-version: tuinity version git-tuinity-"8056d13"

**Additional context**
none

**Comment by Th3Shadowbroker** [comment]
Status
- [ ] Can be replicated
- [ ] Check source of problem
- [ ] Implement fix
