### ISSUE TITLE
Add mining permit

### ISSUE THREAD

**Issue by Darutan92** [Th3Shadowbroker/OuroborosMines#62]
Adding permission to drop ore from mine blocks. Only those with this permit can extract ore from the mine.

**Comment by Th3Shadowbroker** [comment]
I hope I can implement it in the next few days. I had to do some major changes this week laying the foundation for #40.
Thank you for your patience 🙂

**Comment by Th3Shadowbroker** [comment]
@Darutan92 Good news! I finished said preparations for #40.
This issue is the next item on my todo-list and will be implemented within the next few days.

**Comment by Darutan92** [comment]
Oh, thanks for informing me. I'm really looking forward to it!02.02.2021, 23:54, "Jens Fischer" <notifications@github.com>:
@Darutan92 Good news! I finished said preparations for #40.
This issue is the next item on my todo-list and will be implemented within the next few days.

**Comment by Th3Shadowbroker** [comment]
A [new dev build](https://jenkins.th3shadowbroker.org/job/OuroborosMines/54/) is available. I've merged it with the temporary fix, so you can use it immediately. This feature will become part of the main branch as soon as #67 is completed 🙂
