### ISSUE TITLE
Implement support for Towny

### ISSUE THREAD

**Issue by Darutan92** [Th3Shadowbroker/OuroborosMines#63]
Now the mines are not protected by the Towny protection, anyone can extract ore from them, not even a representative of the city. It would be great to check whoever mines the ore for belonging to the city, within which the ore block is located, which is broken.

Plugin link - https://www.spigotmc.org/resources/towny-advanced.72694/

**Comment by Th3Shadowbroker** [comment]
I hope I can implement it in the next few days. I'll do some research regarding the Towny API 🙂

**Comment by Th3Shadowbroker** [comment]
Hey @Darutan92,
a [new test-build](https://jenkins.th3shadowbroker.org/job/OuroborosMines/59/) is ready. Towny support will be enabled automatically. To make sure everything's working correctly, the parent region of the town or the town-world (`__global__`) must be flagged as a mining region. Let me know if everything's working as expected 🙂

**Comment by Th3Shadowbroker** [comment]
@Darutan92 Please let me know if you run into any issues 🙂
