### ISSUE TITLE
OuroborosMines is unable to register the flag

### ISSUE THREAD

**Issue by Darutan92** [Th3Shadowbroker/OuroborosMines#66]
When I start a server with a small number of plugins, Ouroboros starts up perfectly (Worldguard is installed), but when there are more than 48 plugins, when the server starts, it gives this error and does not work. I don't even know what else to connect with, other than the number of plugins.

That is, not with the presence or absence of a specific one, but simply with the total number - any over 48 and Ouroboros gives an error and does not load.

1. Install the list of the listed plugins or any other of your own, in the amount of more than 48 pieces, including Ouroboros and WorldGuard.
2. Observe the error with Ouroboros connections to WorldGuard in the console when starting the server.
3. Remove at least one of any plugin. Start the server again. Voila, everything works without errors.

Server-version: yatopia-1.16.5-yatoclip-b21.jar and 1.16.4-paper-275

**Comment by Th3Shadowbroker** [comment]
Hi @Darutan92,
I'm currently investigating this problem.
Even though I don't know the exact cause of this problem, I discovered, that disabling CraftBook helps.
I'll let you know if I find out something new.

**Comment by Th3Shadowbroker** [comment]
I've implemented a fix into a new [dev-build](https://jenkins.th3shadowbroker.org/job/OuroborosMines/48/). 
With the upcoming changes of #40 this will no longer be a problem. Until then, please use the mentioned dev.-build 🙂 
However, I still don't know why this problem didn't occurred in the past 🤔

**Comment by Darutan92** [comment]
> I've implemented a fix into a new [dev-build](https://jenkins.th3shadowbroker.org/job/OuroborosMines/49/).
> With the upcoming changes of #40 this will no longer be a problem. Until then, please use the mentioned dev.-build 
> However, I still don't know why this problem didn't occurred in the past

Thank you, I'll take a look.

**Comment by Darutan92** [comment]
> > I've implemented a fix into a new [dev-build](https://jenkins.th3shadowbroker.org/job/OuroborosMines/49/).
> > With the upcoming changes of #40 this will no longer be a problem. Until then, please use the mentioned dev.-build
> > However, I still don't know why this problem didn't occurred in the past
> 
> Thank you, I'll take a look.

Yes, it works now, thanks!

**Comment by Th3Shadowbroker** [comment]
You're welcome! 🙂
