### ISSUE TITLE
[ItemsAdder] Conflict with loot from custom blocks

### ISSUE THREAD

**Issue by ryxan** [Th3Shadowbroker/OuroborosMines#88]
**Describe the bug**

**To Reproduce**
--
1. I have items adder, latest, and oroboros mines, latest. All dependencies upto date.
2. I have a block/ore setup with multiple different drops all with different percentages. Items adder has a feature called 'drop only first' which only drops the first item that passes the percentage test.
3. So the problem is when manually placing the blocks and mining them, only one drop is produced everytime, but as soon as I setup a mine the drops come, in twos, sometimes 3. One. Not only the desired single drop

Wondering if this is a big with itemsadder or oroboros mines? Since as soon as a mine is created the drops come in multiples.

**Desktop (please complete the following information):**
 - Minecraft-version: 1.19.4
 - Server-version: latest paper, I downloaded it fresh to test again.

**Additional context**
[ItemsAdder-Issue](https://github.com/PluginBugs/Issues-ItemsAdder/issues/2427)

**Comment by Th3Shadowbroker** [comment]
Hello ryxan,
there could be a conflict between the two plugins causing this behaviour. To be able to do some further investigations please send me your configuration used for the created mine. If I can replicate the described behaviour I might be able to create a hotfix for it 🔧

**Comment by ryxan** [comment]
is this all you need?

inherit: false
materials:
  iarunescape:gemrocks_block:
    replacements:
    - bedrock
    cooldown: 10
  coal_ore:
    replacements:
    - stone
    cooldown: 20
  gold_ore:
    replacements:
    - stone
    cooldown: 30
  iron_ore:
    replacements:
    - stone
    cooldown: 40
  emerald_ore:
    replacements:
    - stone
    cooldown: 50
  redstone_ore:
    replacements:
    - stone
    cooldown: 55
  diamond_ore:
    replacements:
    - stone
    cooldown: 120

**Comment by Th3Shadowbroker** [comment]
I were able to replicate the described behaviour. It seems to be caused by the ItemsAdder API not respecting the `drop_only_first` 👀 I've requested confirmation from LoneDev, as this could also be the expected behaviour and OM is just missing the additional logic.
