### ISSUE TITLE
EcoSkills. Not gaining XP after activating mine.

### ISSUE THREAD

**Issue by ryxan** [Th3Shadowbroker/OuroborosMines#90]
**Describe the bug**

I have EcoSkills plugin. I gain XP fine cutting wood, I'd assume it's the same for mining. But I've just tried on wood regeneration. 
As soon as I add the flag to world edit to activate the OM mine. I no longer get XP for the skill.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Minecraft-version: 1.19.4
 - Server-version: latest paper.
 - I'm using Fastasyncworldedit.

**Additional context**

**Comment by Th3Shadowbroker** [comment]
Woodcutting isn't supported at the moment but I should be able to add it easily.

**Comment by Th3Shadowbroker** [comment]
@ryxan There you go. Let me know if you run into any problems.
(I had to put the jar into an archive as jar files are not supported by GitHub)

[OuroborosMines_v1.12.3-SNAPSHOT-DEV.jar.zip](https://github.com/Th3Shadowbroker/OuroborosMines/files/11185788/OuroborosMines_v1.12.3-SNAPSHOT-DEV.jar.zip)

**Comment by ryxan** [comment]
looks like its working now. Thanks very much! your support is impressive!

**Comment by Th3Shadowbroker** [comment]
Happy to hear that 😄 
Thank you!
